language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t boris90/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true boris90/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-957814146075"
  bucket_path: "docker-react"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY